### ISSUE TITLE
API error message not exposed

### ISSUE THREAD

**Issue by takluyver** [GearPlug/bitbucket-python#10]
I had some issues with authentication (I needed to use my bitbucket username, rather than my email address - I'm not sure in what conditions this applies). bitbucket-python exposed this as `NotAuthenticatedError: None`.

The code looks like it's expecting error messages wrapped JSON, but in this scenario, the message is delivered as a 'plain text' response body, not JSON, saying:

```
Login failed due to incorrect login credentials or method.
For information on authentication methods for Bitbucket Cloud APIs, visit:
    https://developer.atlassian.com/cloud/bitbucket/rest/intro/#authentication
If you are unsure of which login details or login method to use, visit:
    https://support.atlassian.com/bitbucket-cloud/docs/log-into-or-connect-to-bitbucket-cloud/
```

This is a minor point, and once I got past it, I was able to do what I needed with bitbucket-python, so thank-you!

**Comment by ingmferrer** [comment]
This should be fixed by @capcom6 

update to the latest version

**Comment by takluyver** [comment]
Thanks!
