### ISSUE TITLE
Release to pypi?

### ISSUE THREAD

**Issue by AWegnerGitHub** [GearPlug/bitbucket-python#3]
I am attempting to use the code in the README 

```
client = Client(user='myemail@example.com', password='REALPASSWORD', owner='OwnerName')
```

But this fails with the following message:

```
TypeError: __init__() got an unexpected keyword argument 'owner'
```

The README on PyPI doesn't have the example with `owner`. Could the newest version be released onto pypi?

**Comment by ingmferrer** [comment]
Solved.

PyPI version was recently updated to 0.2.2

Thanks for reporting.
