### ISSUE TITLE
Filter issues?

### ISSUE THREAD

**Issue by MichalSkoula** [GearPlug/bitbucket-python#9]
Hello,
is there any way I can filter issues in get_issues method? For example return only "new" or "open" issues?

**Comment by capcom6** [comment]
Hello.

You can use sorting and filtering as described in https://developer.atlassian.com/cloud/bitbucket/rest/intro/#filtering by providing `params` dict to `get_issues` method.

```python
client.get_issues(repository_slug, {"q": 'state = "new" OR state = "open"'})
```

**Comment by ingmferrer** [comment]
I'll close this issue, feel free to re open if you still have questions.
